apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:mqapCjt11i5Ss1WY+/PLeQ3xoc03+nFzF6SkuGXVsCSOFLwJx4pJTjjAks9RPVlQUS3NrkhwJidMbF8Ci1CUBLjGhf/egkLMwws+rbstwEiRStzgCo5f0loaDzpWN7HlWLh8051R4n892EJtLK/iMhYmU6nGRuIC2YfC2cihqslVitZygbsw6U0JBoYyQMagppsfpDzv0QvsR9lOY8ZcGgngQnui4EC+BJGoX2v/DGKtYFp4BoxrUzmL7WuhiKPjRUOqvdZiDHpxuZHYIytCMw8QOqXHwLq0ttmchhj+2ws9y6XAR32xdkNFRE8=,iv:Ojf91z0CB9KybJfQ7wYhqict9v50sm3C+37ixqGv2Ps=,tag:W0JNtZjkNn5GDdEO8qV/0w==,type:str]
kind: Secret
metadata:
    name: audiobs-tunnelcreds
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWDFkTjFRSGM5SDQwNENz
            cUlPRTd1QWlCWUlUUG12SlVIZXgyQ092TTAwCndZdlVZRVhIdHY0RGxxeHhmcW1z
            ZmFGb2U1c3ovZHVRQlZrTFR6ejRWc2MKLS0tIDRobUxwQ0Y2L3ZMb0tyUDVnME9M
            K0haOU1CdUR5M1UzUjRjdjZKV25TaVUKGNY1qBg1gjvBM4NPPi1U4mlsvTIq9YMY
            19sl3aTQjUlDHx228iWJ0/lgoVRQ0RMCrZ1WGHGggsybqUHetbzS5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxudrgy7x6885yycvahksj5xl6kjhdqpwdqtgznm9r304kv22emqehe8n9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T14:32:11Z"
    mac: ENC[AES256_GCM,data:KV9rxWmEZV7Slv+S0KNm2HERdZfNxzjWpx3X7wF008rjgXkJ13yYGz6c8aLywI7x+4Wem1jFeFRqLYoXp/1YjTiv3KHwSEkEtrps34c7k8pBN6HNKarBTGk6CYdh+JfwFAjU+QLv5K9FNWC3iA4B/XToNI/GnSmBoSM8hOLDgAA=,iv:QkhoqosOBwa8jmgZ/UtHTD/znPttTVI+mvX7kPf5NgU=,tag:PyIPpK5m40QGo8mIAD4LEQ==,type:str]
    version: 3.13.2
