apiVersion: v1
data:
    audiobs-tunnelcreds.json: ENC[AES256_GCM,data:/ZUa7PTAtVi7Os0yNFZzay1+akmdfvsiLr/k9G9rR505OlaNKr7QHU0OFCXnvrwQagtGoN5EBMvQzKgeQd8BjPMj0L5zSRQW9t/zMlHoe8X9E2KJXcxptSBFCxq8tkGTQdeQ9RZgbp0Gv4uKcbO/cnTmK/qzhNfDrU2NzyK+0X83sv0WA+pNhuyDqseSszQvChdp0rftUsU2B7bsxWtYriyXgchkXbamxPoUHurJ82gtCNAAl8kZ6Z3qgCvak6vqbpa723Isu++hphVn/V/+Qv5fEXXO25Z15X+DM/6H/KONBozS5nS9t8edTEE=,iv:v2ybe9tbGZSsYJBm28E/qTlEGlZug4/I032ryPHCfDQ=,tag:lIYmXMvKJqFlHH4Mv94jwg==,type:str]
kind: Secret
metadata:
    name: audiobs-tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbEFONjFORkovanpkYnpR
            NUFVaTJySkdadnRaNFA5dVBKOHFlWmtzSzEwCmJQQm5nMkV3eDVYUkk1VzF2TXZl
            SUZXdW13RDJaYVp2VGtrdk5MaVRobmsKLS0tIGJiWDJ0TmtwSjIwTFBwR3Z2Z2ZV
            Mmp5V2RTVExlcFdVL1ZNZTBPRXA0cE0KxSstXO98Y/nZPFbJy6VO/0jvzUgbbBBv
            10YO3TLzUu7+t4edgUAL0mvTm3dskwmENG5Qa5b/J83wKbBVBjswJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxudrgy7x6885yycvahksj5xl6kjhdqpwdqtgznm9r304kv22emqehe8n9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T01:50:13Z"
    mac: ENC[AES256_GCM,data:OBxrwD/2DAcoxOuTdU8wMf0lL6Xt0plGi/KU4Y39ywDcLfvjXq/y7yu73bpD8WVCIZgeR752qS7JTJCVeo4wnS+XKz+VxtXt/R9Qb4PsPpKWTlb+SdS9Q4C6fbTegrLMRFzLFhC6mGGiCALT1fI+wn93Jbk2+iC6Gqh0SlB6dSU=,iv:wN7YAjJ5b80aGV9Vq2vKhOxSV8MRkZrhSE4bpYNeYLE=,tag:rKcY7S730mOGRKvp9OtuMg==,type:str]
    version: 3.13.2
