apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: audiobs
  namespace: audiobs
spec:
  ingressClassName: traefik
  rules:
    - host: audiobs.d11s.space
      http:
        paths:
          - backend:
              service:
                name: audiobs
                port:
                  number: 3005
            path: /
            pathType: Prefix
