apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audiobs
resources:
  - ../../base/audiobs/
  - cloudflare.yaml
  - configmap.yaml
  #- ingress.yaml
  - homelab-tunnel-credentials.yaml
  - homelab-audiobs-superuser-credentials.yaml
