apiVersion: v1
data:
    homelab-tunnelcreds.json: ENC[AES256_GCM,data:qLOXk3ljSVuvfY1rKFNAlJQeqw4M+iW0StiBbYJbKFSJtKCXfheIqzFUBkVrQb2sxSsM09IDMZ1iIBrDO4Z27H/etIteEKTFvLK7q05L2W3I/I11uOOFJOuQC+q5lTo3Dj8ov9v4Q/bK5woJrpWslM2Wzy2OVhPuk0eW+bCjq4HOiHVzc9gyC+TuC10Qkwy/AMEqXZOG7R9hK70X/8AtLM4ta7s+uVRll/7p6CtjJJB05A5XvMqSNiMRWd8cgSK94ilHOFbXDiKA/+5iDzbFjn93lZqEpAKsmQCHlmHFSwXmtqqfuHbmYollClQ=,iv:D8nwrdIIWfb/5UXAtuQTn7NIsAl5gCXmWE27nlMOk5c=,tag:oWIU5NAQXWdRDDfeAspDsg==,type:str]
kind: Secret
metadata:
    name: homelab-tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlU0krNDI1NG1qdWxmZk96
            dWI3dHZLYnlMdTdXSFArL2pwUXd1d1ZzUGg0ClQ1RkprYXU3SmV6WnoxL2cvZ2R6
            d0ZVR2ZUSGNUQ3UyUk5CdzRPWVlaSUUKLS0tIGhsYXM2UzdoVndmaVBuNGU0RzdB
            dVFDbWdrMzZhNittYlFFaXc1clN1NjQKtoFyq9603FuxcyrWMPkhnvpu/SuVCQ02
            9OyB8r+W+pzpvzAvekVkwL+k8PUNILSWjyNWx1vP+hnm1IaEQUTXlQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxudrgy7x6885yycvahksj5xl6kjhdqpwdqtgznm9r304kv22emqehe8n9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T13:00:37Z"
    mac: ENC[AES256_GCM,data:kmggc8dfkTz5AoSVPDL14HNQQPXSh+RUB3XSLlsfUrUMtu0W5fcYJv8slHusNCEKOPMEr9zHZHEBLWr3aFXl/fxHao2E27fcSWdjdPwUz/GFrq9MGX8z5mPO3WLE9MioycNRlxkTQ7VXNx7KleJuvAtU+z4pPWNU7FKWc1XJ1Sw=,iv:NbdM41dx66Dse+rCrS8Qt/b+lHOFLfp1u5e0Rc7shVY=,tag:gY6yvgDJ9G+4AH721pQm3Q==,type:str]
    version: 3.13.2
