apiVersion: v1
data:
    homelab-tunnelcreds.json: ENC[AES256_GCM,data:aIObgs/FjrnQRj2CYZ+Bej0zOD/V7lgfwK+lph3Q3paqOR0tVjnycGCzTk9zGHT/XVV5+FlbHQ0FW+SqfCl2J19LkFauzguiScgAUqvjp9mo/7uTtTOu33q5qKdO/y9VlrOz0U+lKy7UYRXmHPw8kXPF4KfVbqXLDhINmZILq2cSVs7/Pu0f7Rm0QkG/6ekkvt7BsNjLSPfkVs/UKtJtj0M/bGb5IBmRoPSO6vWw9Sij7h7ugrOgX8lLcYiqeJkdBPxymUL3+HGzZhRdMvamFoPjGTlGG+TagqrWboxUQ0nzR+OOtyh0RvAugZA=,iv:f9f5dDsDWgYwbTicWByOEbg/mWrX5AohRRXzqMBwUQY=,tag:3bDETD/5WuN7RyYhsX/9Bw==,type:str]
kind: Secret
metadata:
    name: homelab-tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSlVSajV3NXZNTi9jTzI4
            Rks3NU9vcmE4Y2xCa3luRWZOZXZvT25lTHdjCndFL0gzd0drd0h0VHRDVGc2ZWRi
            NSthRlNjK3B2eHNubzBhMHMwY3d2UW8KLS0tIDIwNy9zSmRMUmF0RHNTbmtpS1F4
            aE14VjFTVmExMXp6ckY1M2V5Ynk1Mm8KGTPURuG+1pIfChFBgTxHWuixG5IZNn0n
            bZGUPoegjowJbmcZnUG6dN+krD6gASf4KbFhGgss0H24wdoz2ZQv4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxudrgy7x6885yycvahksj5xl6kjhdqpwdqtgznm9r304kv22emqehe8n9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T14:15:52Z"
    mac: ENC[AES256_GCM,data:To+vfg3uB3h9pfmyHEzUdjZjz3WOihknhmsRpkuzO3rHO4TdSBjmbnOQX5KwNXnH2O4LIin9baCt+WTwBj5dWiE+K8bhN1n7Yxcp4YpYfjRLGBV2/2Q532dYWEZDAVzJY9LG4sO2dAKHKJtuEKbA5DpMLtSqMO7yW81I05hgXHM=,iv:DMH5soCt/cX0qNU8D1O7OLU0a1pk/Z3lq4DbqDy+KW0=,tag:c0ZoM1hswLOd0DTDtvYFyQ==,type:str]
    version: 3.13.2
