apiVersion: v1
data:
    homelab-linkding-superuser-credentials.json: ENC[AES256_GCM,data:8e88QSdKK18KTAGZ,iv:rYSY4RD8htOAvJfbBZFaRSshjem2KEEis2Q9RAVofok=,tag:lDBwsa7rldLKwIUPWRgNSg==,type:str]
kind: Secret
metadata:
    name: homelab-linkding-superuser-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORXNGdnZiYzVoUDh2eXpI
            SEVmZGpPd0hCTlY3MXZvbTFmZEZFZW9xUVU0CmJBRlF1bWdzbndrUTNwUjRwWmVl
            UDRoZWJhYVBlMVlkQUZzTU0ydnRSRnMKLS0tIFgzRUgvTnhvb21jc3lDRHBhUXBX
            VkIvRXhEMEh0NXpMY0d5V3FQblVQemsKLQoFdfW28nfVhm1eBk0uKTXQSAlH4nHY
            xdOHGCjnV2Y2wsGgzlvBExvplxn5RZR/qg208HmDjgkmVJdEUPgV0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxudrgy7x6885yycvahksj5xl6kjhdqpwdqtgznm9r304kv22emqehe8n9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T13:33:45Z"
    mac: ENC[AES256_GCM,data:EPD/aBe9eVktNfkNQCOyj+vIT6vmc3uSs/gq+LZjxYBffD/7qhPSX85/tQSuJ3DrOFlpQQKR4Wg0XfvUF0mH7v4WtdpPQq4IoI04sXHIgrMAnNzvsm/8MGkStaRorC4SB8ERNOxVfDRgX1zMb7DmjEUkd9viz2Jtecal9k/hbeI=,iv:/T+ErLzLyf99PfZt6NO4vizSvF7OyMp+I74e4YOlSY0=,tag:BUStVwTBN2V5j3IpvgiYkw==,type:str]
    version: 3.13.2
