apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:tDl2yl+RFpI=,iv:mbCIAShMubeUPggIuyVq1jK20VQGnacVLaYn2itxvmI=,tag:XlOew/fk6Ir9qoxlMk3a6A==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:Xh9OtHP4TsP4IffP,iv:TILc+2yKLZt50lBgH9xrDyi2qsp4EETEfsNiL9sx24s=,tag:k8PxIv3pMRgIoM7DlzjJAw==,type:str]
kind: Secret
metadata:
    name: homelab-linkding-superuser-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQ2NiRmVpUFI0UHd6Zytr
            aDB1OC9zbXFqeC9KYXNzUnc5cVd4RHNsVDFjCnpVQUpiSW1BeGFDWFg3YTlSTy84
            cUI4Ty9kOW9VaXR5OWRuV3NKWkdEWW8KLS0tIEc2VWZVVE5ucUlIb3hwNUtpbnkr
            eDZ0RTFPSWYxSy9tWlFEVUd5Wm1wL0kK7OeydrM7Qy7ZiaChojgX+URp/37IHwO2
            4IuhxXvmS7TBLFdWXxaB+nGigbwyKu9ikH4hJS2CzTo13oFRqpK9tA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxudrgy7x6885yycvahksj5xl6kjhdqpwdqtgznm9r304kv22emqehe8n9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T15:26:22Z"
    mac: ENC[AES256_GCM,data:J3ml42m8lu+ANEFd5jUNq178Q0OX5aMqAjTOeZlJ4I/hiPwoLWv2Wa3cOV2rG3YDjOHtqIhS3hP/GSVijVX2rnIhAGmOe63CvXi0wf3N8dhZI+TOD3awP2gBdB7DYSwQH2Ej5/jRevSJTBv6rU9RcZ4TUCZEh0CV5RqXoNYeAoI=,iv:WDbXFm6cc4NAcqUgrRLsoe1iOeUnRbfgjpI7HdkUQX8=,tag:/kucuepEs/BylWkHfuGmzw==,type:str]
    version: 3.13.2
