apiVersion: v1
data:
    password: ENC[AES256_GCM,data:5WrblsBdvCQ=,iv:FPrs5XggMtJJnLhYukggR+B6s4XDyDdK2I7wQRC6Id4=,tag:NRW8+IeavQPQ85k81P68Dw==,type:str]
    user: ENC[AES256_GCM,data:nJ0NklZ8Vrk=,iv:MmxJMOY+iNrsfCtOOhzk1+xb94jnHeMYCll02RylNtQ=,tag:fpXzz7cldhsJS1JkUWUqlw==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUL3FXMXFQMmQ0V01DU0ph
            Ky9CcFFYbDZuNklqVWZtNFVmd0c1alh0YWtzCmN3bXFSVUpWMHpXRE1Ud2N0N2ha
            ejY2Vk5UQTE4VWhSTUErVjNjaHdOWmcKLS0tIHhweWZzTzlYTHlUazRoN3Ezb0kr
            QUkwTXBIb1R5SVJZQ3ZWZk9xd09uU3cKbhyC78SwP4+S9LWGcgJIjAHg3tmpTPUZ
            YQgHQwf+VyJKpyJ0CcYha5oJGa1oEhWAFU/haJeXtrzRmKAHSEUslg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxudrgy7x6885yycvahksj5xl6kjhdqpwdqtgznm9r304kv22emqehe8n9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T11:46:49Z"
    mac: ENC[AES256_GCM,data:5q++vJNgfjpDVGq4O9ayuPDrKC/TlMYKqPSnLSUjp71JPLNQwUlKTlSowE62RiOSyZqaJf5FVEG+keleDmUJP56E+pfh3LMU47r7+/JHypd7nlUBnsfkapz8C0sif190b0XL3BkuSs6DBBEQlYgZSbIg7ngndE3emUxRibv/bgw=,iv:OxOJ1+4b7xwN2KseD8xR8mmZZImtj5unf/lcP52OYFA=,tag:oKLZQ8y0Z/Q6ybk5vrR+Vg==,type:str]
    version: 3.13.2
