apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobs
  template:
    metadata:
      labels:
        app: audiobs
    spec:
      #securityContext:
        #fsGroup: 33 # www-data group ID
        #runAsUser: 33 # www-data user ID
        #runAsGroup: 33 # www-data group ID
      containers:
        - name: audiobs
          image: ghcr.io/advplyr/audiobookshelf:2.33.0
          envFrom:
            #- secretRef:
                #name: homelab-audiobs-superuser-credentials
            - configMapRef:
                name: audiobs-configmap
          ports:
            - containerPort: 3005
          restart: unless-stopped
          securityContext:
            allowPrivilegeEscalation: true

          volumeMounts:
            - name: audiobs-config
              mountPath: /config
            - name: audiobs-metadata
              mountPath: /metadata
            - name: audiobs-audiobooks
              mountPath: /audiobooks
            - name: audiobs-postcasts
              mountPath: /postcasts
      volumes:
        - name: audiobs-config
          persistentVolumeClaim:
            claimName: audiobs-config-pvc
        - name: audiobs-metadata
          persistentVolumeClaim:
            claimName: audiobs-metadata-pvc
        - name: audiobs-audiobooks
          persistentVolumeClaim:
            claimName: audiobs-audiobooks-pvc
        - name: audiobs-podcasts
          persistentVolumeClaim:
            claimName: audiobs-podcasts-pvc
