apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:+1L0lweZQa/O03EHB7s6kxsRAq4ASrTDGPihMIxhDRVoN7eyky6yJKn948g=,iv:60dTvLNWPQeiWktkkVdg5nAl5g/WMyIaYqlbw48K+pw=,tag:2/RT5lF8g+DbxIgqRM52yA==,type:str]
    admin-user: ENC[AES256_GCM,data:jWBK4XGEsQ4=,iv:3gbawDUtSRgJrREwgawTGPSO5nelojWC8AAKAw8Ud2s=,tag:uWIPQblht1Qp6rHuxoLtDw==,type:str]
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUkZEVjNOam5SV2JMVW1M
            OVpYUjF2bHVuWjZLZXBJa1BTbURydmNjSkJzCmJmZzJRdU5lNVN2V1dvbDhLT3FE
            NkdpaVk1Uld6OEtFaGtYeEFBQ1FkZFEKLS0tIGJSUUFCWFh2NjFYbm9ZWk1GMDZj
            NEdhaG5xRnhMZWxOYWFBMXV3b1ZQa28KV542Z7EWKCfZHps76/Jjf0L6SlAR2swx
            DOUgTzOhkktvrQyxJnK1DzZHMvDrDHh5eD1CKqm3ogsKECJUu3T/GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxudrgy7x6885yycvahksj5xl6kjhdqpwdqtgznm9r304kv22emqehe8n9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T04:31:12Z"
    mac: ENC[AES256_GCM,data:oKqh/gWTOrmFhA5O+/tT7L9KWJTive0Wln0iXPodsE2fV9fLuvZVZ307Frdg12ABksqbAk2x1418L/e8SAdBHBIRuzLH9qjWW7N3T1DCHnHV/q8P4M6RX+cOd6WDLQl+1Jf9PEefscI9BjiIKBvWyMV1f0cbG33/6La/ctTAtT8=,iv:FJ2JwP4jViKyZFMfsj9UWi7JkTxiq6KRyjKzpH8+EH4=,tag:RPrDBWx/Auk+dFgNO4Paww==,type:str]
    version: 3.13.2
