apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:fCQjszI+LNQ=,iv:t1KhwZ9d5bgJX0y+Q587SBPRnSnNfc90OrJ8hXjDujw=,tag:IMULX3T6QBHcRlJ2LkEPGQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:wm9rIuPh7egR0mxk,iv:CNRP4Me3tSgiw3c3IQRvwjnwfS/Vy+DTG6P6yDebdvE=,tag:VTO4FDG33tw8rAapJQk2jw==,type:str]
kind: Secret
metadata:
    name: homelab-linkding-superuser-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2T1d6dXBhVThyTURkTk9I
            WjlDNXlROTAwWFJnOFZBSUhmQVZKK1JJQVZvCmUyVUh6eHd5Q1Y3RmNsSVh2aFM1
            ZjhzWlJZS3lVeWZSSVFLeXR1Z2p1S00KLS0tIGRqRENubXJhc1ZHR3hGYy9UUTBs
            eHNqZEJRU2tqWmJ4NHJOYUs1cFVQNWsKOZc7/NkPr3t9TTZ5/Haz2jdIedNoHp3w
            IdrO3mySl1Uv8Xht32yb1PB3+ZWOakBcUWK2j6TUEJImh3zUnKjLKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxudrgy7x6885yycvahksj5xl6kjhdqpwdqtgznm9r304kv22emqehe8n9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T14:30:19Z"
    mac: ENC[AES256_GCM,data:/Dh0IEbac0Z9VpEKOwgO4OcgFhykiX8qiywiFdi9vveBSVFJEuXnrwV+Gp7y9OSR6eu4mPuRnhtAiEtSoqjAvE6SdYOc4YfKXOqVy8Sn6rMHHXhCVnrsnbXe8WxQB+4skFox71JhekegMmTeUHvLC1Jd9wARWbryd84YQaWZsfU=,iv:ZZI/gHLuyoeW0xPw6jKjovHSM1J3W6c2SmaMBIF1JeE=,tag:JVSHY0HLMFxJMWQ57thF4w==,type:str]
    version: 3.13.2
