apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:fMcGjBuV5n9yjuWv0rIrN6qc+j5KDzzsDXbI6z1cHQ549bkVA2aKNwecvdkm0Teo23+A39o0T5Y=,iv:b8e1ERxEbEmtb+NO8dJx1J+afdQQkNqfu1fX24ix3nY=,tag:XV2D43n0WR4hO5M9wf1cjQ==,type:str]
kind: Secret
metadata:
    name: renovate-container-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOHVQSGUyVk9jaUkzcFdD
            WDNCNThBT3hqWEhPL2VoNzkrQWNvVWZMTWkwCmZnTVErU3J3bXZQTDlvQm5DTFZ0
            TmpCMW1QaGxBNGw3MnJ3QkwrTTVNN3MKLS0tIFhIRnVlRWY4MkgzNDB2dDhhUExT
            c0g1TDRKN3h3dTlUTHVVd25ZRTdHRFEKluqe8IkSCq5/qql/FBO6KXHqYmbsgIE/
            x6ar2D5Uj55AF+fgE8k5c8bBjhn50Kcy49MDgDD7b3KG7TdWvSEr8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxudrgy7x6885yycvahksj5xl6kjhdqpwdqtgznm9r304kv22emqehe8n9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T07:54:02Z"
    mac: ENC[AES256_GCM,data:hvyuyRXeS5aQqnbh4+MTwEFbsuuoGxSWfVYnM6JRa8seluCmpqefmeiY9q/BnVEqq8WTzX5zc9Evq7B5a29RMkXL3gj8EIn8qawd+k0MJInsVDHHv/kJBY8HtIZABlHE5GUPFrMNlYZMeo4nTSoWNMW0Kkginfmmy6eG8lOowQA=,iv:4eQUgcc/eIDRuS7wcMTjb6aoSQIgGPIMMJ4zv1D+/7E=,tag:3CAVrCVQxlp/trbalIGPBg==,type:str]
    version: 3.13.2
